### ISSUE TITLE
ActiveModel::MissingAttributeError: can't write unknown attribute ``

### ISSUE THREAD

**Issue by nathanpalmer** [godaddy/activerecord-delay_touching#3] opened 2015-04-03 21:05 UTC
Just pulled in this gem to try it out and running into this error. This is running on Rails 4.2.

```
   (4.3ms)  ROLLBACK
ActiveModel::MissingAttributeError: can't write unknown attribute ``
	from /Users/nathan/.rvm/gems/ruby-2.1.5/bundler/gems/rails-79728982aa75/activerecord/lib/active_record/attribute.rb:124:in `with_value_from_database'
	from /Users/nathan/.rvm/gems/ruby-2.1.5/bundler/gems/rails-79728982aa75/activerecord/lib/active_record/attribute_set.rb:39:in `write_from_user'
	from /Users/nathan/.rvm/gems/ruby-2.1.5/bundler/gems/rails-79728982aa75/activerecord/lib/active_record/attribute_methods/write.rb:74:in `write_attribute_with_type_cast'
	from /Users/nathan/.rvm/gems/ruby-2.1.5/bundler/gems/rails-79728982aa75/activerecord/lib/active_record/attribute_methods/write.rb:56:in `write_attribute'
	from /Users/nathan/.rvm/gems/ruby-2.1.5/bundler/gems/rails-79728982aa75/activerecord/lib/active_record/attribute_methods/dirty.rb:96:in `write_attribute'
	from /Users/nathan/.rvm/gems/ruby-2.1.5/bundler/gems/rails-79728982aa75/activerecord/lib/active_record/persistence.rb:464:in `block in touch'
	from /Users/nathan/.rvm/gems/ruby-2.1.5/bundler/gems/rails-79728982aa75/activerecord/lib/active_record/persistence.rb:462:in `each'
	from /Users/nathan/.rvm/gems/ruby-2.1.5/bundler/gems/rails-79728982aa75/activerecord/lib/active_record/persistence.rb:462:in `touch'
	from /Users/nathan/.rvm/gems/ruby-2.1.5/bundler/gems/rails-79728982aa75/activerecord/lib/active_record/callbacks.rb:296:in `block in touch'
	from /Users/nathan/.rvm/gems/ruby-2.1.5/bundler/gems/rails-79728982aa75/activesupport/lib/active_support/callbacks.rb:117:in `call'
	from /Users/nathan/.rvm/gems/ruby-2.1.5/bundler/gems/rails-79728982aa75/activesupport/lib/active_support/callbacks.rb:117:in `call'
	from /Users/nathan/.rvm/gems/ruby-2.1.5/bundler/gems/rails-79728982aa75/activesupport/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
	from /Users/nathan/.rvm/gems/ruby-2.1.5/bundler/gems/rails-79728982aa75/activesupport/lib/active_support/callbacks.rb:505:in `call'
	from /Users/nathan/.rvm/gems/ruby-2.1.5/bundler/gems/rails-79728982aa75/activesupport/lib/active_support/callbacks.rb:505:in `call'
	from /Users/nathan/.rvm/gems/ruby-2.1.5/bundler/gems/rails-79728982aa75/activesupport/lib/active_support/callbacks.rb:92:in `_run_callbacks'
	from /Users/nathan/.rvm/gems/ruby-2.1.5/bundler/gems/rails-79728982aa75/activesupport/lib/active_support/callbacks.rb:776:in `_run_touch_callbacks'
... 13 levels...
	from /Users/nathan/.rvm/gems/ruby-2.1.5/bundler/gems/rails-79728982aa75/railties/lib/rails/commands/console.rb:9:in `start'
	from /Users/nathan/.rvm/gems/ruby-2.1.5/bundler/gems/rails-79728982aa75/railties/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /Users/nathan/.rvm/gems/ruby-2.1.5/bundler/gems/rails-79728982aa75/railties/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/nathan/.rvm/gems/ruby-2.1.5/bundler/gems/rails-79728982aa75/railties/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/nathan/.rvm/gems/ruby-2.1.5/bundler/gems/rails-79728982aa75/activesupport/lib/active_support/dependencies.rb:274:in `require'
	from /Users/nathan/.rvm/gems/ruby-2.1.5/bundler/gems/rails-79728982aa75/activesupport/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/nathan/.rvm/gems/ruby-2.1.5/bundler/gems/rails-79728982aa75/activesupport/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/nathan/.rvm/gems/ruby-2.1.5/bundler/gems/rails-79728982aa75/activesupport/lib/active_support/dependencies.rb:274:in `require'
	from /Users/nathan/Source/CrowdOx/Api/bin/rails:8:in `<top (required)>'
	from /Users/nathan/.rvm/gems/ruby-2.1.5/bundler/gems/rails-79728982aa75/activesupport/lib/active_support/dependencies.rb:268:in `load'
	from /Users/nathan/.rvm/gems/ruby-2.1.5/bundler/gems/rails-79728982aa75/activesupport/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/nathan/.rvm/gems/ruby-2.1.5/bundler/gems/rails-79728982aa75/activesupport/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/nathan/.rvm/gems/ruby-2.1.5/bundler/gems/rails-79728982aa75/activesupport/lib/active_support/dependencies.rb:268:in `load'
	from /Users/nathan/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Users/nathan/.rvm/rubies/ruby-2.1.5/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```

This happens right after I try to run touch on a model. Thoughts? I haven't gone through the source code verses what is in ActiveRecord but I'm curious if you're running on an older version of Rails than I.

**Comment by nfm** [comment] 2015-04-27 06:14
I can confirm this is an issue. I was running `activerecord-delay_touching` on Rails 4.1, and after updating to 4.2 am seeing this exception for the majority of my tests.

I think it may be related to 4.2 introducing the ability to touch multiple attributes (https://github.com/rails/rails/pull/14423), but I haven't confirmed that yet.

**Comment by nfm** [comment] 2015-04-27 06:27
Yes, looks like this is in fact the case. @roelbondoc has a fork with a fix applied here: https://github.com/roelbondoc/activerecord-delay_touching/commit/145cfc00d59e20c9d85cd6f6c7bcefe62e3db27a

**Comment by alexbel** [comment] 2015-04-27 13:22
A fix will be very desirable, because a native support of delay touching in rails will be only in version 5. They plan to release that this autumn.

**Comment by mtuckergd** [comment] 2015-04-27 18:57
Hey folks. Thanks for the PR. We'll take a look and try to get something updated ASAP. From a cursory glance, the fork from @roelbondoc looks reasonable. Just need to run some specs around it to verify.

**Comment by mtuckergd** [comment] 2015-05-07 07:04
Turns out, roelbondoc@145cfc0 does not properly fix this issue and specs were failing all over the place. I have munged together a possible fix; PR is in play. If this passes review, we'll push up a new gem version for ActiveRecord 4.2+ support.

**Comment by mtuckergd** [comment] 2015-05-07 19:53
Fixed by https://github.com/godaddy/activerecord-delay_touching/issues/5. 

Pushed two new versions of the gem to RubyGems.org. 

Version 0.0.2 has a revised ActiveRecord dependency to version < 4.2 and will be the canonical gem for activerecord prior to the 4.2 change.

Version 1.0.0 is the updated code and has a dependency on ActiveRecord >= 4.2.

**Closed by mtuckergd** 2015-05-07 19:53 UTC

**Comment by nathanpalmer** [comment] 2015-05-07 20:21
This is great. Thanks!
